#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout )
        i3-msg exit
        ;;
    
    *)
        echo "Usage: $0 {lock|logout|}"
        exit 2
esac

exit 0
